### ISSUE TITLE
make the client package goinstallable

### ISSUE THREAD

**Issue by kr** [ha/doozer#2]
It would probably look something like

```
goinstall github.com/ha/doozer/src/pkg/client
```

Client uses only one other doozer package: doozer/proto.

**Comment by rogpeppe** [comment]
might i suggest that the package identifier could be a little less generic?

if i've got a program that uses the doozer client, then the default
name for the Client type is "client.Client" - which doesn't really
say anything useful - there are many "client" types in the go libraries.

better would be to name it "doozer" (or perhaps "doozer_client"),
then the code would read more nicely IMHO:

```
package mypackage
import (
  "github.com/ha/doozer"
)
func attach() *doozer.Client {
    return doozer.New(name, addr)
}
```

the naming for the server side packages is less important because
they will be less used.

**Comment by kr** [comment]
Yes, that sounds perfect.

Perhaps we should even split the server stuff out into a separate repository.
